server:
  port: 7101

spring:
  application:
    name: travel-config
  security:
    user:
      name: admin
      password: a
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PYC2020/yc81.git
          default-label: main        # 一定要配置，因为github升级后，已经没有 master 分支了， 而config server 默认是 master,  现在已经是 main

eureka:
  client:
    register-with-eureka: true    #是否要注册到eureka, 解决eureka启动时报错
    service-url:
      defaultZone: http://admin:a@localhost:7301/eureka
  instance:
    prefer-ip-address: true
    instance-id: travel-config1

